name: GitHub Pages

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow_ref }}

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/gh-pages.yml
      - package.json
      - package-lock.json
      - tsconfig.json
      - vite.config.ts
      - public/**
      - src/**

jobs:
  gh-pages:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write
      contents: read

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Configure
        uses: actions/configure-pages@v4
        with:
          token: ${{ secrets.ADMIN_ORG_ACCESS_TOKEN }}
          enablement: true

      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
